version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" # NATS client port
      - "8222:8222" # NATS monitoring/HTTP port
    command: "--http_port 8222" # Example command to enable HTTP monitoring
